#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DIR="$ROOT_DIR/skills"
DIST_DIR="$ROOT_DIR/dist"
BUILD_DIR="$DIST_DIR/.build"
CODEX_STAGE="$BUILD_DIR/codex-import"
CLAUDE_STAGE="$BUILD_DIR/claude-code-import"

rm -rf "$BUILD_DIR"
mkdir -p "$CODEX_STAGE/skills" "$CLAUDE_STAGE/.claude/skills" "$DIST_DIR"

mapfile -t SKILL_DIRS < <(find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d | sort)

SKILL_NAMES=()
for skill_dir in "${SKILL_DIRS[@]}"; do
  if [[ ! -f "$skill_dir/SKILL.md" ]]; then
    continue
  fi

  skill_name="$(basename "$skill_dir")"
  SKILL_NAMES+=("$skill_name")
  cp -R "$skill_dir" "$CODEX_STAGE/skills/$skill_name"
  cp -R "$skill_dir" "$CLAUDE_STAGE/.claude/skills/$skill_name"
done

cat > "$DIST_DIR/README.md" <<'EOF'
# best-skills bundle output

This directory is generated by `scripts/build-import-bundles.sh`.

## Files

- `best-skills-codex.zip`: unzip into `$CODEX_HOME/`
- `best-skills-claude-code.zip`: unzip into your home directory or project root so `.claude/skills/` lands in the right place
- `codex-import/`: unpacked Codex bundle contents
- `claude-code-import/`: unpacked Claude Code bundle contents
- `skills-manifest.txt`: included skill directories
EOF

printf '%s\n' "${SKILL_NAMES[@]}" > "$DIST_DIR/skills-manifest.txt"

cp -R "$CODEX_STAGE" "$DIST_DIR/codex-import"
cp -R "$CLAUDE_STAGE" "$DIST_DIR/claude-code-import"

python3 - "$DIST_DIR" <<'PY'
import os
import shutil
import sys

dist_dir = sys.argv[1]

artifacts = [
    ("best-skills-codex", os.path.join(dist_dir, "codex-import")),
    ("best-skills-claude-code", os.path.join(dist_dir, "claude-code-import")),
]

for archive_name, source_dir in artifacts:
    archive_path = os.path.join(dist_dir, archive_name)
    if os.path.exists(archive_path + ".zip"):
        os.remove(archive_path + ".zip")
    shutil.make_archive(archive_path, "zip", root_dir=source_dir)
PY

rm -rf "$BUILD_DIR"

echo "Built bundles:"
echo "  $DIST_DIR/best-skills-codex.zip"
echo "  $DIST_DIR/best-skills-claude-code.zip"
echo "  $DIST_DIR/codex-import"
echo "  $DIST_DIR/claude-code-import"
